# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.18.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.18.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/pieterboersma/Desktop/battlesimulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/pieterboersma/Desktop/battlesimulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.18.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.18.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pieterboersma/Desktop/battlesimulator/CMakeFiles /Users/pieterboersma/Desktop/battlesimulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pieterboersma/Desktop/battlesimulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tmpl8_2018-01

# Build rule for target.
Tmpl8_2018-01: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tmpl8_2018-01
.PHONY : Tmpl8_2018-01

# fast build rule for target.
Tmpl8_2018-01/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/build
.PHONY : Tmpl8_2018-01/fast

explosion.o: explosion.cpp.o

.PHONY : explosion.o

# target to build an object file
explosion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/explosion.cpp.o
.PHONY : explosion.cpp.o

explosion.i: explosion.cpp.i

.PHONY : explosion.i

# target to preprocess a source file
explosion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/explosion.cpp.i
.PHONY : explosion.cpp.i

explosion.s: explosion.cpp.s

.PHONY : explosion.s

# target to generate assembly for a file
explosion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/explosion.cpp.s
.PHONY : explosion.cpp.s

game.o: game.cpp.o

.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i

.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s

.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/game.cpp.s
.PHONY : game.cpp.s

particle_beam.o: particle_beam.cpp.o

.PHONY : particle_beam.o

# target to build an object file
particle_beam.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/particle_beam.cpp.o
.PHONY : particle_beam.cpp.o

particle_beam.i: particle_beam.cpp.i

.PHONY : particle_beam.i

# target to preprocess a source file
particle_beam.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/particle_beam.cpp.i
.PHONY : particle_beam.cpp.i

particle_beam.s: particle_beam.cpp.s

.PHONY : particle_beam.s

# target to generate assembly for a file
particle_beam.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/particle_beam.cpp.s
.PHONY : particle_beam.cpp.s

rocket.o: rocket.cpp.o

.PHONY : rocket.o

# target to build an object file
rocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/rocket.cpp.o
.PHONY : rocket.cpp.o

rocket.i: rocket.cpp.i

.PHONY : rocket.i

# target to preprocess a source file
rocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/rocket.cpp.i
.PHONY : rocket.cpp.i

rocket.s: rocket.cpp.s

.PHONY : rocket.s

# target to generate assembly for a file
rocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/rocket.cpp.s
.PHONY : rocket.cpp.s

smoke.o: smoke.cpp.o

.PHONY : smoke.o

# target to build an object file
smoke.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/smoke.cpp.o
.PHONY : smoke.cpp.o

smoke.i: smoke.cpp.i

.PHONY : smoke.i

# target to preprocess a source file
smoke.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/smoke.cpp.i
.PHONY : smoke.cpp.i

smoke.s: smoke.cpp.s

.PHONY : smoke.s

# target to generate assembly for a file
smoke.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/smoke.cpp.s
.PHONY : smoke.cpp.s

surface.o: surface.cpp.o

.PHONY : surface.o

# target to build an object file
surface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/surface.cpp.o
.PHONY : surface.cpp.o

surface.i: surface.cpp.i

.PHONY : surface.i

# target to preprocess a source file
surface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/surface.cpp.i
.PHONY : surface.cpp.i

surface.s: surface.cpp.s

.PHONY : surface.s

# target to generate assembly for a file
surface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/surface.cpp.s
.PHONY : surface.cpp.s

tank.o: tank.cpp.o

.PHONY : tank.o

# target to build an object file
tank.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/tank.cpp.o
.PHONY : tank.cpp.o

tank.i: tank.cpp.i

.PHONY : tank.i

# target to preprocess a source file
tank.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/tank.cpp.i
.PHONY : tank.cpp.i

tank.s: tank.cpp.s

.PHONY : tank.s

# target to generate assembly for a file
tank.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/tank.cpp.s
.PHONY : tank.cpp.s

template.o: template.cpp.o

.PHONY : template.o

# target to build an object file
template.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/template.cpp.o
.PHONY : template.cpp.o

template.i: template.cpp.i

.PHONY : template.i

# target to preprocess a source file
template.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/template.cpp.i
.PHONY : template.cpp.i

template.s: template.cpp.s

.PHONY : template.s

# target to generate assembly for a file
template.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tmpl8_2018-01.dir/build.make CMakeFiles/Tmpl8_2018-01.dir/template.cpp.s
.PHONY : template.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Tmpl8_2018-01"
	@echo "... explosion.o"
	@echo "... explosion.i"
	@echo "... explosion.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... particle_beam.o"
	@echo "... particle_beam.i"
	@echo "... particle_beam.s"
	@echo "... rocket.o"
	@echo "... rocket.i"
	@echo "... rocket.s"
	@echo "... smoke.o"
	@echo "... smoke.i"
	@echo "... smoke.s"
	@echo "... surface.o"
	@echo "... surface.i"
	@echo "... surface.s"
	@echo "... tank.o"
	@echo "... tank.i"
	@echo "... tank.s"
	@echo "... template.o"
	@echo "... template.i"
	@echo "... template.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

